# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

# --- !Downs
INSERT INTO people (name, age) VALUES ('Juan', 20)
drop table "people" if exists;

